image: wcr.io/mira/docker-maven:3.5.0-jdk9.0.1

stages:
  - maven_build
  - maven_deploy
  - trigger
    
maven_build:
  stage: maven_build
  script:
    - export
    - echo $MAVEN_SETTINGS_XML > settings.xml
    - mvn -B -s settings.xml clean install
  artifacts:
    when: always
    paths:
    - "*/target/test-output"
    - "*/target/surefire-reports"
    - "*/target/failsafe-reports"
  tags:
    - docker
    - privileged

maven_deploy:
  stage: maven_deploy
  script:
    - export
    - echo $MAVEN_SETTINGS_XML > settings.xml
    - > 
      mvn -B -DaltDeploymentRepository=snapshots::default::$MAVEN_SNAPSHOTS_URL 
      -DskipTests=true -s settings.xml clean install deploy
  artifacts:
    when: always
    paths:
    - "*/target/test-output"
    - "*/target/surefire-reports"
    - "*/target/failsafe-reports"
  tags:
    - docker
    - privileged

trigger-coherence-grpc:
  stage: trigger
  script:
    - >
      curl --insecure --request POST --form "token=$CI_JOB_TOKEN" --form ref=master 
      https://gitlab-odx.oracle.com/api/v4/projects/572/trigger/pipeline

